# Based on http://lmjohns3.com/2015/06/using-travis-ci-with-miniconda-scipy-and-nose.html
# Tweaked to specify versions on everything for stability.
language: python
python:
  - '3.6'

cache: apt

services:
  - docker

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - conda install -c bioconda pysam
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Prefer stability to having the latest
  #- conda update --yes conda

install:
  - conda install -c conda-forge --yes python=$TRAVIS_PYTHON_VERSION scipy
  - pip install -r requirements.txt
  - python setup.py install

script:
  - ./test.sh
